# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/

exclude: (.*/env/.*)  # Exclude conda environments

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
    -   id: insert-license
        files: \.py$
        args: [ --license-filepath, .github/disclaimer.txt ]
        # We exclude the versioneer files, since those are open domain
        exclude: ^(versioneer.py|conda_project/_version.py)
