channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - flake8
  - mypy
  - pytest
  - pylint
  - pytest-cov
  - pytest-mock
  - pre-commit
  - conda-lock>=1.2
  - pydantic
  - ruamel.yaml
  - setuptools-scm
