name: test-conda-project
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-lock>=2.1.1
  - pexpect
  - lockfile
  - ruamel.yaml
  - pydantic
  - pytest
  - pytest-cov
  - pytest-mock
  - shellingham
  - python-dotenv
  - fsspec
  - python-libarchive-c
