name: cmds-and-vars

environments:
  default:
    - environment.yml

variables:
  FOO: bar

commands:
  default:
    cmd: python -c 'import os;print(os.getenv("FOO"))'
    environment: default
  notdefault:
    cmd: python -c 'import os;print(os.getenv("FOO"))'
    environment: default
    variables:
      FOO: baz
