{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject['project'] %}

{% set name = project['name'] %}
{% set version = VERSION %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{version}} {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    {% for name, reference in project['scripts'].items() %}
    - {{ name }} = {{ reference }}
    {% endfor %}

requirements:
  host:
    - python {{ project['requires-python'] }}
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python {{ project['requires-python'] }}
    - conda-lock >=2.2
    - lockfile
    - pexpect
    - ruamel.yaml
    - pydantic
    - shellingham
    - python-dotenv
    - fsspec
    - python-libarchive-c
    - setuptools

test:
  imports:
    - conda_project
  commands:
    - conda-project --help
    - conda-project --version
    - python -c "from conda_project import __version__; assert __version__ == \"{{ version }}\""

about:
  home: {{ project['urls']['repository'] }}
  summary: {{ project['description'] }}
  license: {{ project['license']['text'] }}
  license_file: LICENSE
